### ISSUE TITLE
Can't run shabdakosh

### ISSUE THREAD

**Issue by scimad** [TheDeltaFinders/Shabdakosh#2]
After successfully running the installation script, I got the following error while trying to run `shabdakosh`.

```
Traceback (most recent call last):
  File "/usr/local/bin/shabdakosh", line 4, in <module>
    __import__('pkg_resources').run_script('shabdakosh==0.0.1', 'shabdakosh')
  File "/home/scimad/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/scimad/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/shabdakosh-0.0.1-py3.6.egg/EGG-INFO/scripts/shabdakosh", line 63, in <module>
  File "/home/scimad/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/scimad/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/scimad/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/scimad/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/shabdakosh-0.0.1-py3.6.egg/EGG-INFO/scripts/shabdakosh", line 47, in process_request
  File "/usr/local/lib/python3.6/dist-packages/shabdakosh-0.0.1-py3.6.egg/EGG-INFO/scripts/shabdakosh", line 22, in show_text
  File "/usr/local/lib/python3.6/dist-packages/shabdakosh-0.0.1-py3.6.egg/shabdakosh/readpdf.py", line 46, in get_text
  File "/usr/local/lib/python3.6/dist-packages/shabdakosh-0.0.1-py3.6.egg/shabdakosh/readpdf.py", line 126, in get_word_font
  File "/usr/local/lib/python3.6/dist-packages/shabdakosh-0.0.1-py3.6.egg/shabdakosh/readpdf.py", line 67, in get_font_char
FileNotFoundError: [Errno 2] No such file or directory: '../res/Large/split/splitted_438-438.pdf'
```

How to fix this and run `shabdakosh` succesfully?

I tried to fix the path `../res/Large/split/splitted_438-438.pdf` to `../res/splitted_438-438.pdf` as that seemed to me as the relevant path, but that didn't work.

**Comment by pranphy** [comment]
Should be fixed now. Check 3ae049a2. Let me know if it is fixed.

**Comment by scimad** [comment]
Works now!
